import { Geist, Geist_Mono } from "next/font/google";
// Google fonts imported via Next.js font optimization

import "./globals.css";
// Global application styles

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/thumbs";
import "swiper/css/zoom";
import "swiper/css/free-mode";
// Swiper global styles required across the app

import Header from "@/components/layout/header/Header";
// Main application header (navigation, search, user actions)

import Footer from "@/components/layout/footer/Footer";
// Global footer component

import { ReduxProvider } from "@/core/store/Provider";
// Redux provider wrapper for global state management

import { Toaster } from "react-hot-toast";
// Toast notification system

/* ------------------------------------------------------------
   Font configuration
------------------------------------------------------------ */
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable for sans font
  subsets: ["latin"], // Character subsets
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable for mono font
  subsets: ["latin"],
});

/* ------------------------------------------------------------
   Application metadata (SEO)
------------------------------------------------------------ */
export const metadata = {
  title: "ShoppersLink",
  description: "Generated by finger tips innovation ltd.",
};

/* ------------------------------------------------------------
   Root layout component
------------------------------------------------------------ */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply global font variables to body */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Redux provider enables global state access */}
        <ReduxProvider>
          {/* Global toast notification handler */}
          <Toaster
            position="top-center"
            toastOptions={{
              style: {
                background: "#333",
                color: "#fff",
                borderRadius: "8px",
                padding: "10px 16px",
              },
            }}
          />

          {/* Application header */}
          <Header />

          {/* Page content */}
          {children}

          {/* Application footer */}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
