const COLOR_MAP = {
  maroon: "#800000",
  purple: "#800080",
  navy: "#1e293b",
  "navy blue": "#1e293b",
  "royal blue": "#4169e1",
  teal: "#008080",
  olive: "#808000",
  magenta: "#ff00ff",
  crimson: "#dc143c",
  gold: "#ffd700",
  silver: "#c0c0c0",
  bronze: "#cd7f32",
  beige: "#f5f5dc",
  ivory: "#fffff0",
  lavender: "#e6e6fa",
  turquoise: "#40e0d0",
  coral: "#ff7f50",
  salmon: "#fa8072",
  khaki: "#f0e68c",
  indigo: "#4b0082",
  violet: "#ee82ee",
  plum: "#dda0dd",
  orchid: "#da70d6",
  fuchsia: "#ff00ff",
  lime: "#00ff00",
  aqua: "#00ffff",
  cyan: "#00ffff",
  chocolate: "#d2691e",
  tan: "#d2b48c",
  sienna: "#a0522d",
  peru: "#cd853f",
  saddlebrown: "#8b4513",
  darkred: "#8b0000",
  firebrick: "#b22222",
  brown: "#a52a2a",
  darkgreen: "#006400",
  forestgreen: "#228b22",
  seagreen: "#2e8b57",
  darkolivegreen: "#556b2f",
  midnightblue: "#191970",
  slateblue: "#6a5acd",
  darkslateblue: "#483d8b",

  /* --- added colors --- */
  aliceblue: "#f0f8ff",
  antiquewhite: "#faebd7",
  aquamarine: "#7fffd4",
  azure: "#f0ffff",
  black: "#000000",
  blanchedalmond: "#ffebcd",
  blue: "#0000ff",
  blueviolet: "#8a2be2",
  cadetblue: "#5f9ea0",
  chartreuse: "#7fff00",
  cornflowerblue: "#6495ed",
  cornsilk: "#fff8dc",
  darkcyan: "#008b8b",
  darkgoldenrod: "#b8860b",
  darkgray: "#a9a9a9",
  darkgrey: "#a9a9a9",
  darkkhaki: "#bdb76b",
  darkmagenta: "#8b008b",
  darkorchid: "#9932cc",
  darksalmon: "#e9967a",
  darkseagreen: "#8fbc8f",
  darkslategray: "#2f4f4f",
  darkslategrey: "#2f4f4f",
  darkturquoise: "#00ced1",
  darkviolet: "#9400d3",
  deeppink: "#ff1493",
  deepskyblue: "#00bfff",
  dimgray: "#696969",
  dimgrey: "#696969",
  dodgerblue: "#1e90ff",
  floralwhite: "#fffaf0",
  gainsboro: "#dcdcdc",
  ghostwhite: "#f8f8ff",
  goldenrod: "#daa520",
  gray: "#808080",
  grey: "#808080",
  green: "#008000",
  greenyellow: "#adff2f",
  honeydew: "#f0fff0",
  hotpink: "#ff69b4",
  indianred: "#cd5c5c",
  lavenderblush: "#fff0f5",
  lawngreen: "#7cfc00",
  lemonchiffon: "#fffacd",
  lightblue: "#add8e6",
  lightcoral: "#f08080",
  lightcyan: "#e0ffff",
  lightgoldenrodyellow: "#fafad2",
  lightgray: "#d3d3d3",
  lightgrey: "#d3d3d3",
  lightgreen: "#90ee90",
  lightpink: "#ffb6c1",
  lightsalmon: "#ffa07a",
  lightseagreen: "#20b2aa",
  lightskyblue: "#87cefa",
  lightslategray: "#778899",
  lightslategrey: "#778899",
  lightsteelblue: "#b0c4de",
  lightyellow: "#ffffe0",
  limegreen: "#32cd32",
  linen: "#faf0e6",
  mediumaquamarine: "#66cdaa",
  mediumblue: "#0000cd",
  mediumorchid: "#ba55d3",
  mediumpurple: "#9370db",
  mediumseagreen: "#3cb371",
  mediumslateblue: "#7b68ee",
  mediumspringgreen: "#00fa9a",
  mediumturquoise: "#48d1cc",
  mediumvioletred: "#c71585",
  moccasin: "#ffe4b5",
  navajowhite: "#ffdead",
  oldlace: "#fdf5e6",
  olivedrab: "#6b8e23",
  orange: "#ffa500",
  orangered: "#ff4500",
  palegoldenrod: "#eee8aa",
  palegreen: "#98fb98",
  paleturquoise: "#afeeee",
  palevioletred: "#db7093",
  papayawhip: "#ffefd5",
  peachpuff: "#ffdab9",
  pink: "#ffc0cb",
  powderblue: "#b0e0e6",
  rebeccapurple: "#663399",
  red: "#ff0000",
  rosybrown: "#bc8f8f",
  sandybrown: "#f4a460",
  seashell: "#fff5ee",
  skyblue: "#87ceeb",
  slategray: "#708090",
  slategrey: "#708090",
  snow: "#fffafa",
  springgreen: "#00ff7f",
  steelblue: "#4682b4",
  thistle: "#d8bfd8",
  tomato: "#ff6347",
  wheat: "#f5deb3",
  white: "#ffffff",
  whitesmoke: "#f5f5f5",
  yellow: "#ffff00",
  yellowgreen: "#9acd32",

  /* some brand / descriptive variants */
  "off-white": "#f8f4ef",
  "ivory white": "#fffff0",
  cream: "#fffdd0",
  eggplant: "#311b0b",
  charcoal: "#36454f",
  "steel gray": "#2b2f33",
  "dusty rose": "#c08081",
  blush: "#f2b8a0",
  mint: "#98ff98",
  seafoam: "#7fe5b0",
  pearl: "#eae0c8",
  copper: "#b87333",
  "rose gold": "#b76e79",
  champagne: "#f7e7ce",
  "neon pink": "#ff6ec7",
  "neon green": "#39ff14",
  "neon yellow": "#ffff33",
  "matte black": "#101010",
  gunmetal: "#2a3439",
  midnight: "#121212",
  "sky navy": "#0b1f3b",
  denim: "#1560bd",
  cerulean: "#007ba7",
  "azure blue": "#007fff",
  cornsilk: "#fff8dc",
};

const COLOR_FAMILIES = [
  // BLACK FAMILY
  {
    color: "#101010",
    keys: [
      "black",
      "jet",
      "coal",
      "charcoal",
      "midnight",
      "ink",
      "noir",
      "matte black",
      "carbon",
      "pitch",
      "onyx",
      "ebony",
    ],
  },

  // WHITE FAMILY
  {
    color: "#f8f4ef",
    keys: [
      "white",
      "off white",
      "off-white",
      "ivory",
      "cream",
      "snow",
      "pearl",
      "eggshell",
      "chalk",
      "milk",
      "alabaster",
    ],
  },

  // BLUE FAMILY
  {
    color: "#2563eb",
    keys: [
      "blue",
      "navy",
      "sky",
      "ocean",
      "royal",
      "denim",
      "azure",
      "cobalt",
      "indigo",
      "sapphire",
      "cerulean",
      "steel blue",
      "ice blue",
      "powder blue",
      "baby blue",
      "midnight blue",
      "aqua blue",
    ],
  },

  // GREEN FAMILY
  {
    color: "#16a34a",
    keys: [
      "green",
      "olive",
      "mint",
      "forest",
      "emerald",
      "jade",
      "sea green",
      "bottle green",
      "parrot",
      "leaf",
      "pista",
      "sage",
      "moss",
      "lime",
      "neon green",
      "army green",
    ],
  },

  // RED FAMILY
  {
    color: "#dc2626",
    keys: [
      "red",
      "maroon",
      "crimson",
      "wine",
      "burgundy",
      "cherry",
      "ruby",
      "brick",
      "blood red",
      "scarlet",
      "rust",
      "oxblood",
    ],
  },

  // PINK FAMILY
  {
    color: "#f472b6",
    keys: [
      "pink",
      "rose",
      "blush",
      "baby pink",
      "hot pink",
      "dusty rose",
      "salmon",
      "coral",
      "peach",
      "fuchsia",
      "magenta",
    ],
  },

  // YELLOW / GOLD FAMILY
  {
    color: "#facc15",
    keys: [
      "yellow",
      "gold",
      "golden",
      "mustard",
      "amber",
      "honey",
      "lemon",
      "sun",
      "saffron",
      "champagne",
      "wheat",
    ],
  },

  // ORANGE FAMILY
  {
    color: "#fb923c",
    keys: [
      "orange",
      "burnt orange",
      "rust orange",
      "tangerine",
      "pumpkin",
      "carrot",
      "apricot",
      "terracotta",
    ],
  },

  // PURPLE FAMILY
  {
    color: "#7c3aed",
    keys: [
      "purple",
      "violet",
      "plum",
      "lavender",
      "orchid",
      "eggplant",
      "grape",
      "mauve",
      "lilac",
    ],
  },

  // BROWN FAMILY
  {
    color: "#92400e",
    keys: [
      "brown",
      "tan",
      "coffee",
      "chocolate",
      "mocha",
      "camel",
      "beige",
      "khaki",
      "sand",
      "earth",
      "wood",
      "cinnamon",
    ],
  },

  // GREY FAMILY
  {
    color: "#9ca3af",
    keys: [
      "grey",
      "gray",
      "ash",
      "smoke",
      "silver",
      "slate",
      "stone",
      "graphite",
      "cement",
      "cloud",
    ],
  },

  // MULTI / SPECIAL
  {
    color: "#60a5fa",
    keys: ["multi", "mixed", "combo", "printed", "abstract", "pattern"],
  },
];

export function smartColor(name) {
  if (!name) return "#9ca3af";

  const key = name.toLowerCase().trim();

  // 1️⃣ Exact map
  if (COLOR_MAP[key]) return COLOR_MAP[key];

  // 2️⃣ Keyword family match
  for (const family of COLOR_FAMILIES) {
    if (family.keys.some((k) => key.includes(k))) {
      return family.color;
    }
  }

  // 3️⃣ Safe CSS named colors
  const SAFE = ["black", "white", "red", "blue", "green", "gray"];
  if (SAFE.includes(key)) return key;

  // 4️⃣ Ultimate fallback (neutral, not random)
  return "#cbd5e1";
}
